# Generated by Django 5.0.1 on 2024-01-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_longtext_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtext',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
