# Generated by Django 5.0.1 on 2024-01-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_longtext_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtext',
            name='state',
            field=models.CharField(default='private', max_length=50),
        ),
    ]
