# Generated by Django 5.0.1 on 2024-01-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_longtext_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longtext',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
    ]
